SOURCES=$(shell echo *.cpp)
OBJECTS=$(SOURCES:.cpp=.o)

LIBPEDSOURCES=$(shell echo ../libpedsim/*.cpp)
LIBPEDOBJECTS=$(LIBPEDSOURCES:.cpp=.o)

LIBPEDCUDASOURCES=$(shell echo ../libpedsim/*.cu)
LIBPEDCUDAOBJECTS=$(LIBPEDSOURCES:.cu=.co)

TARGET=demo
QT_HEADERS=$(shell qmake -query QT_INSTALL_HEADERS)
QTINCLUDES=-I$(QT_HEADERS) -I$(QT_HEADERS)/QtWidgets -I$(QT_HEADERS)/QtGui -I$(QT_HEADERS)/QtCore
CUDA_PATH ?= /usr/local/cuda
INCPATH=-I../libpedsim -I$(CUDA_PATH)/include
LIBPATH=-L../libpedsim -L$(CUDA_PATH)/lib64
CXXFLAGS=-g -fPIC $(INCPATH) $(QTINCLUDES) $(LIBPATH) -fopenmp
LIBS = -lQt5Widgets -lQt5Gui -lQt5Core -lpedsim -ltinyxml2
LDFLAGS+="-Wl,-rpath,$(PWD)/libpedsim,-rpath,$(PWD)/../libpedsim"

MOCFILES=QTSimulation.moc

include config.mk
# Add CUDA paths and libraries if CUDA_AVAILABLE is set
ifdef CUDA_AVAILABLE
LIBPATH += -L/usr/local/cuda/lib64
LIBS += -lcudart
endif


all: $(TARGET)

$(TARGET): $(OBJECTS) $(MOCFILES)
	g++ $(CXXFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(LDFLAGS)

%.o: %.cpp %.moc
	g++ $(CXXFLAGS) $(INCPATH) -c -o $@ $<

%.moc: %.h %.cpp
	moc $(DEFINES) $(INCPATH) -i $< -o $@

clean:
	-rm $(TARGET) $(OBJECTS) $(MOCFILES)
